parameters:
    btn_component.provider.container_node_content.class: Btn\ComponentBundle\Provider\ContainerNodeContentProvider

services:
    btn_component.provider.container_node_content:
        class: %btn_component.provider.container_node_content.class%
        arguments:
            renderRouteName:   %btn_component.container.show_route_name%
        tags:
            - { name: btn_node.content_provider }
