services:

    btn_component.provider.node_content:
        class: Btn\ComponentBundle\Provider\NodeContentProvider
        arguments:
            containersProvider: @btn_component.container_provider
            renderRouteName:    %btn_component.container.show_route_name%
        tags:
            - { name: btn_nodes.content_provider }
