services:

    btn_webplatform.provider.node_content:
        class: Btn\WebplatformBundle\Provider\NodeContentProvider
        arguments:
            containersProvider: @btn_webplatform.container_provider
            renderRouteName:    %btn_webplatform.container_show_route_name%
        tags:
            - { name: btn_nodes.content_provider }
