parameters:
    btn_webplatform.container_provider.default.class: Btn\WebplatformBundle\Provider\ContainerProvider
    btn_webplatform.component_provider.default.class: Btn\WebplatformBundle\Provider\ComponentProvider
    btn_webplatform.provider.default.class: Btn\WebplatformBundle\Provider\Provider
    btn_webplatform.hydrator.default.class: Btn\WebplatformBundle\Hydrator\Hydrator
    btn_webplatform.renderer.default.class: Btn\WebplatformBundle\Renderer\Renderer
    btn_webplatform.container_manager.default.class: Btn\WebplatformBundle\Manager\ContainerManager
    btn_webplatform.manager.default.class: Btn\WebplatformBundle\Manager\Manager

    btn_webplatform.event_listener.component_subscriber.class: Btn\WebplatformBundle\EventListener\ComponentSubscriber
