_btn_webplatform_routing_control:
    resource: "@BtnWebplatformBundle/Resources/config/routing/control.yml"
    prefix: /control

_btn_webplatform_routing_front:
    resource: "@BtnWebplatformBundle/Resources/config/routing/front.yml"
    prefix: /
