_btn_component_routing_control:
    resource: "@BtnComponentBundle/Resources/config/routing/control.yml"
    prefix: /control

_btn_component_routing_front:
    resource: "@BtnComponentBundle/Resources/config/routing/front.yml"
    prefix: /
