parameters:
    btn_component.container_provider.default.class: Btn\ComponentBundle\Provider\ContainerProvider
    btn_component.component_provider.default.class: Btn\ComponentBundle\Provider\ComponentProvider
    btn_component.provider.default.class: Btn\ComponentBundle\Provider\Provider
    btn_component.hydrator.default.class: Btn\ComponentBundle\Hydrator\Hydrator
    btn_component.renderer.default.class: Btn\ComponentBundle\Renderer\Renderer
    btn_component.container_manager.default.class: Btn\ComponentBundle\Manager\ContainerManager
    btn_component.manager.default.class: Btn\ComponentBundle\Manager\Manager
    btn_component.event_listener.component_subscriber.class: Btn\ComponentBundle\EventListener\ComponentSubscriber
    btn_component.manager.layout.class: Btn\ComponentBundle\Manager\LayoutManager

services:
    btn_component.provider.component:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: ['%btn_component.component.class%']

    btn_component.provider.container:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: ['%btn_component.container.class%']

    btn_component.container_provider.default:
        class: %btn_component.container_provider.default.class%
        arguments:
            entityProvider: @btn_component.provider.container
        calls:
            - [setContainers, ['%btn_component.containers%']]

    btn_component.component_provider.default:
        class: %btn_component.component_provider.default.class%
        arguments:
            componentClass: %btn_component.component.class%
            em: @doctrine.orm.entity_manager

    btn_component.provider.default:
        class: %btn_component.provider.default.class%
        arguments:
            containerProvider: @btn_component.container_provider
            componentProvider: @btn_component.component_provider

    btn_component.hydrator.default:
        class: %btn_component.hydrator.default.class%

    btn_component.abstract_component_hydrator:
        class: Btn\ComponentBundle\Hydrator\AbstractComponentHydrator
        abstract: true

    btn_component.abstract_component_renderer:
        class: Btn\ComponentBundle\Renderer\AbstractComponentRenderer
        abstract: true
        arguments:
            twig: @twig

    btn_component.renderer.default:
        class: %btn_component.renderer.default.class%
        arguments:
            provider: @btn_component.provider

    btn_component.abstract_component_manager:
        class: Btn\ComponentBundle\Manager\AbstractComponentManager
        abstract: true
        arguments:
            em: @doctrine.orm.entity_manager

    btn_component.container_manager.default:
        class: %btn_component.container_manager.default.class%
        arguments:
            em: @doctrine.orm.entity_manager

    btn_component.manager.default:
        class: %btn_component.manager.default.class%
        arguments:
            provider: @btn_component.provider
            containerManager: @btn_component.container_manager
            components: %btn_component.components%

    btn_component.event_listener.hydrator_subscriber:
        class: Btn\ComponentBundle\EventListener\HydratorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            hydrator: @btn_component.hydrator

    btn_component.event_listener.component_subscriber:
        class: %btn_component.event_listener.component_subscriber.class%
        arguments:
            componentClass: %btn_component.component.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    btn_component.manager.layout:
        class: %btn_component.manager.layout.class%
        arguments:
            twig: @twig
            layouts: %btn_component.layouts%
