services:

    btn_webplatform.container_provider.default:
        class: %btn_webplatform.container_provider.default.class%
        arguments:
            containerClass: %btn_webplatform.container.class%
            em: @doctrine.orm.entity_manager
        calls:
            - [setContainers, ['%btn_webplatform.containers%']]

    btn_webplatform.component_provider.default:
        class: %btn_webplatform.component_provider.default.class%
        arguments:
            componentClass: %btn_webplatform.component.class%
            em: @doctrine.orm.entity_manager

    btn_webplatform.provider.default:
        class: %btn_webplatform.provider.default.class%
        arguments:
            containerProvider: @btn_webplatform.container_provider
            componentProvider: @btn_webplatform.component_provider

    btn_webplatform.hydrator.default:
        class: %btn_webplatform.hydrator.default.class%

    btn_webplatform.abstract_component_hydrator:
        class: Btn\WebplatformBundle\Hydrator\AbstractComponentHydrator
        abstract: true

    btn_webplatform.abstract_component_renderer:
        class: Btn\WebplatformBundle\Renderer\AbstractComponentRenderer
        abstract: true
        arguments:
            twig: @twig

    btn_webplatform.renderer.default:
        class: %btn_webplatform.renderer.default.class%
        arguments:
            provider: @btn_webplatform.provider

    btn_webplatform.twig.renderer_extension:
        class: Btn\WebplatformBundle\Twig\RendererExtension
        arguments:
            renderer: @btn_webplatform.renderer
        tags:
            - { name: twig.extension }

    btn_webplatform.twig.provider_extension:
        class: Btn\WebplatformBundle\Twig\ProviderExtension
        arguments:
            provider: @btn_webplatform.provider
        tags:
            - { name: twig.extension }

    btn_webplatform.abstract_component_manager:
        class: Btn\WebplatformBundle\Manager\AbstractComponentManager
        abstract: true
        arguments:
            em: @doctrine.orm.entity_manager

    btn_webplatform.container_manager.default:
        class: %btn_webplatform.container_manager.default.class%
        arguments:
            em: @doctrine.orm.entity_manager

    btn_webplatform.manager.default:
        class: %btn_webplatform.manager.default.class%
        arguments:
            provider: @btn_webplatform.provider
            containerManager: @btn_webplatform.container_manager
            components: %btn_webplatform.components%

    btn_webplatform.event_listener.hydrator_subscriber:
        class: Btn\WebplatformBundle\EventListener\HydratorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            hydrator: @btn_webplatform.hydrator

    btn_webplatform.event_listener.component_subscriber:
        class: %btn_webplatform.event_listener.component_subscriber.class%
        arguments:
            componentClass: %btn_webplatform.component.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    btn_webplatform.form.component:
        class: Btn\WebplatformBundle\Form\ComponentForm
        arguments:
            manager: @btn_webplatform.manager
        tags:
            - { name: form.type, alias: btn_webplatform_form_component }

    btn_webplatform.form_handler.component:
        class: Btn\WebplatformBundle\Form\Handler\ComponentFormHandler
        arguments:
            manager: @btn_webplatform.manager

    btn_webplatform.form.container:
        class: Btn\WebplatformBundle\Form\ContainerForm
        arguments:
            manager: @btn_webplatform.manager
        tags:
            - { name: form.type, alias: btn_webplatform_form_container }

    btn_webplatform.form_handler.container:
        class: Btn\WebplatformBundle\Form\Handler\ContainerFormHandler
        arguments:
            manager: @btn_webplatform.manager

    btn_webplatform.form.type.component_type:
        class: Btn\WebplatformBundle\Form\Type\ComponentTypeType
        arguments:
            manager: @btn_webplatform.manager
        tags:
            - { name: form.type, alias: btn_webplatform_type_component_type }
