services:
    btn_component.container_provider.default:
        class: %btn_component.container_provider.default.class%
        arguments:
            containerClass: %btn_component.container.class%
            em: @doctrine.orm.entity_manager
        calls:
            - [setContainers, ['%btn_component.containers%']]

    btn_component.component_provider.default:
        class: %btn_component.component_provider.default.class%
        arguments:
            componentClass: %btn_component.component.class%
            em: @doctrine.orm.entity_manager

    btn_component.provider.default:
        class: %btn_component.provider.default.class%
        arguments:
            containerProvider: @btn_component.container_provider
            componentProvider: @btn_component.component_provider

    btn_component.hydrator.default:
        class: %btn_component.hydrator.default.class%

    btn_component.abstract_component_hydrator:
        class: Btn\ComponentBundle\Hydrator\AbstractComponentHydrator
        abstract: true

    btn_component.abstract_component_renderer:
        class: Btn\ComponentBundle\Renderer\AbstractComponentRenderer
        abstract: true
        arguments:
            twig: @twig

    btn_component.renderer.default:
        class: %btn_component.renderer.default.class%
        arguments:
            provider: @btn_component.provider

    btn_component.twig.renderer_extension:
        class: Btn\ComponentBundle\Twig\RendererExtension
        arguments:
            renderer: @btn_component.renderer
        tags:
            - { name: twig.extension }

    btn_component.twig.provider_extension:
        class: Btn\ComponentBundle\Twig\ProviderExtension
        arguments:
            provider: @btn_component.provider
        tags:
            - { name: twig.extension }

    btn_component.abstract_component_manager:
        class: Btn\ComponentBundle\Manager\AbstractComponentManager
        abstract: true
        arguments:
            em: @doctrine.orm.entity_manager

    btn_component.container_manager.default:
        class: %btn_component.container_manager.default.class%
        arguments:
            em: @doctrine.orm.entity_manager

    btn_component.manager.default:
        class: %btn_component.manager.default.class%
        arguments:
            provider: @btn_component.provider
            containerManager: @btn_component.container_manager
            components: %btn_component.components%

    btn_component.event_listener.hydrator_subscriber:
        class: Btn\ComponentBundle\EventListener\HydratorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            hydrator: @btn_component.hydrator

    btn_component.event_listener.component_subscriber:
        class: %btn_component.event_listener.component_subscriber.class%
        arguments:
            componentClass: %btn_component.component.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    btn_component.form.component:
        class: Btn\ComponentBundle\Form\ComponentForm
        arguments:
            manager: @btn_component.manager
        tags:
            - { name: form.type, alias: btn_component_form_component }

    btn_component.form_handler.component:
        class: Btn\ComponentBundle\Form\Handler\ComponentFormHandler
        arguments:
            manager: @btn_component.manager

    btn_component.form.container:
        class: Btn\ComponentBundle\Form\ContainerForm
        arguments:
            manager: @btn_component.manager
        tags:
            - { name: form.type, alias: btn_component_form_container }

    btn_component.form_handler.container:
        class: Btn\ComponentBundle\Form\Handler\ContainerFormHandler
        arguments:
            manager: @btn_component.manager

    btn_component.form.type.component_type:
        class: Btn\ComponentBundle\Form\Type\ComponentTypeType
        arguments:
            manager: @btn_component.manager
        tags:
            - { name: form.type, alias: btn_component_type_component_type }

    btn_component.btn_admin_menu_top_item:
        class: Knp\Menu\MenuItem
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_component.container.components", "btn_component_containercontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }
