_btn_component_routing_control_controller_container:
    resource: "@BtnComponentBundle/Controller/ContainerControlController.php"
    type:     annotation

_btn_component_routing_control_controller_component:
    resource: "@BtnComponentBundle/Controller/ComponentControlController.php"
    type:     annotation
