services:
    btn_component.btn_admin_menu_top_item:
        public: false
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_component.container.components", "btn_component_containercontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }
